[project]
name = "fuzzy-traffic-optimization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.19.1",
    "numpy>=2.4.0",
    "packaging>=25.0",
    "scikit-fuzzy>=0.5.0",
]
